import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          {children}
          <Toaster
            richColors
            expand
            position="top-right"
            theme="system"
            className="font-primary"
            visibleToasts={3}
            // icons={{
            //   close: <X className='h-4 w-4' />,
            //   error: <ShieldX className='h-4 w-4' />,
            //   info: <BadgeInfo className='h-4 w-4' />,
            //   loading: <Loader className='h-4 w-4' />,
            //   success: <BadgeCheck className='h-4 w-4' />,
            //   warning: <TriangleAlert className='h-4 w-4' />,
            // }}
          />
        </TooltipProvider>
      </body>
    </html>
  );
}
